/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BacklinkCollectorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  outputFolder: "Backlinks"
};
var BacklinkCollectorPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "collect-backlinks",
      name: "Collect backlinks for current note",
      callback: () => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          this.collectBacklinks(activeFile);
        } else {
          new import_obsidian.Notice("No active note found");
        }
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Collect backlinks").setIcon("links-coming-in").onClick(async () => {
              await this.collectBacklinks(file);
            });
          });
        }
      })
    );
    this.addSettingTab(new BacklinkCollectorSettingTab(this.app, this));
  }
  onunload() {
    console.log("Backlink Collector plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async collectBacklinks(targetFile) {
    const targetNoteName = targetFile.basename;
    new import_obsidian.Notice(`Collecting backlinks for "${targetNoteName}"...`);
    const allFiles = this.app.vault.getMarkdownFiles();
    const backlinks = [];
    for (const file of allFiles) {
      if (this.settings.outputFolder && file.path.startsWith(this.settings.outputFolder + "/")) {
        continue;
      }
      const content = await this.app.vault.read(file);
      const matches = this.findBacklinksInContent(content, targetNoteName);
      if (matches.contexts.length > 0) {
        backlinks.push({
          fileName: file.basename,
          filePath: file.path,
          count: matches.count,
          contexts: matches.contexts
        });
      }
    }
    if (backlinks.length === 0) {
      new import_obsidian.Notice(`No backlinks found for "${targetNoteName}"`);
      return;
    }
    const outputContent = this.generateBacklinkDocument(targetNoteName, backlinks);
    const outputFileName = `${targetNoteName}_backlinks.md`;
    const outputPath = this.settings.outputFolder ? `${this.settings.outputFolder}/${outputFileName}` : outputFileName;
    if (this.settings.outputFolder) {
      const folder = this.app.vault.getAbstractFileByPath(this.settings.outputFolder);
      if (!folder) {
        await this.app.vault.createFolder(this.settings.outputFolder);
      }
    }
    const existingFile = this.app.vault.getAbstractFileByPath(outputPath);
    if (existingFile instanceof import_obsidian.TFile) {
      await this.app.vault.modify(existingFile, outputContent);
    } else {
      await this.app.vault.create(outputPath, outputContent);
    }
    new import_obsidian.Notice(`Backlinks collected! Found ${backlinks.length} files. Saved to ${outputPath}`);
    const newFile = this.app.vault.getAbstractFileByPath(outputPath);
    if (newFile instanceof import_obsidian.TFile) {
      await this.app.workspace.getLeaf().openFile(newFile);
    }
  }
  findBacklinksInContent(content, targetNoteName) {
    const linkPattern = new RegExp(`\\[\\[${targetNoteName}(?:\\|[^\\]]+)?\\]\\]`, "g");
    const matches = content.match(linkPattern);
    if (!matches || matches.length === 0) {
      return { count: 0, contexts: [] };
    }
    const lines = content.split("\n");
    const contexts = [];
    const getIndentLevel = (str) => {
      const match = str.match(/^(\s*)/);
      if (!match)
        return 0;
      return match[0].replace(/\t/g, "    ").length;
    };
    lines.forEach((line, index) => {
      if (line.includes(`[[${targetNoteName}`)) {
        const contextLines = [];
        const currentIndent = getIndentLevel(line);
        contextLines.push(line);
        let nextIndex = index + 1;
        while (nextIndex < lines.length) {
          const nextLine = lines[nextIndex];
          if (nextLine.trim() === "") {
            contextLines.push(nextLine);
            nextIndex++;
            continue;
          }
          const nextIndent = getIndentLevel(nextLine);
          if (nextIndent > currentIndent) {
            contextLines.push(nextLine);
            nextIndex++;
          } else {
            break;
          }
        }
        contexts.push(contextLines.join("\n"));
      }
    });
    return { count: matches.length, contexts };
  }
  generateBacklinkDocument(targetNoteName, backlinks) {
    let content = "";
    backlinks.forEach((backlink, index) => {
      content += `[[${backlink.fileName}]]

`;
      backlink.contexts.forEach((context, ctxIndex) => {
        content += `${context}

`;
      });
      if (index < backlinks.length - 1) {
        content += `---

`;
      }
    });
    return content;
  }
};
var BacklinkCollectorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("\uBC31\uB9C1\uD06C \uBB38\uC11C\uB97C \uC800\uC7A5\uD560 \uD3F4\uB354. \uC774 \uD3F4\uB354 \uC548\uC758 \uD30C\uC77C\uB4E4\uC740 \uBC31\uB9C1\uD06C \uAC80\uC0C9\uC5D0\uC11C \uC790\uB3D9\uC73C\uB85C \uC81C\uC678\uB429\uB2C8\uB2E4.").addText((text) => text.setPlaceholder("Backlinks").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
  }
};
